In [1]:
from fund_analysis.input_data.coal import Coal
import pandas as pd
import datetime as dt

In [2]:
base_products = ['W_1', 'W_2', 'W_3', 'M_1', 'M_2', 'M_3', 'Q_1', 'Q_2', 'Q_3']
base_products = ['W_1', 'W_2', 'M_1', 'M_2']
market_list = ['de', 'fr']
delivery_dict = ['base', 'peak']

# Generate the combinations
products = []
markets = []
delivery = []

for product in base_products:
    for market in market_list:
        for delivery_option in delivery_dict:
            products.append(product)
            markets.append(market)
            delivery.append(delivery_option)

params_dict = {}

params_dict['product_list'] = products

params_dict['market_list'] = markets

params_dict['delivery_list'] = delivery 

params_dict['year_list'] = [None] * len(params_dict['market_list'])
params_dict['ns'] = 2
params_dict['cont'] = False


params_dict['sD'] = dt.datetime(2020,1,1)
params_dict['eD'] = pd.to_datetime(dt.datetime.today().date())
params_dict['eD'] = dt.datetime(2024,8,1)
params_dict['ns'] = 2
params_dict['cont'] = False

In [3]:
coal_inst = Coal(params_dict)

In [4]:
coal_inst.get_da_data()

In [5]:
coal_inst.fut_matrix['api2']

,M_1,M_2,M_3,M_4,M_5,M_6,M_7,M_8,M_9,M_10,...,M_51,M_52,M_53,M_54,M_55,M_56,M_57,M_58,M_59,M_60
datetime,,,,,,,,,,,,,,,,,,,,,
2020-01-02,52.10,53.80,54.50,54.55,54.80,55.30,56.55,57.10,58.10,58.95,...,71.05,70.90,70.80,70.85,70.95,71.05,71.15,71.20,71.30,71.35
2020-01-03,52.75,54.20,55.00,55.20,55.45,56.00,57.30,57.85,58.85,59.40,...,71.80,71.65,71.55,71.60,71.70,71.80,71.90,71.95,72.05,72.10
2020-01-06,52.65,53.75,54.55,55.00,55.55,55.75,57.15,57.70,58.70,59.20,...,72.05,71.90,71.80,71.80,71.95,72.05,72.15,72.20,72.25,72.35
2020-01-07,52.55,53.85,54.80,55.45,55.85,56.05,57.50,58.05,59.10,59.85,...,73.40,73.25,73.15,73.20,73.30,73.40,73.45,73.55,73.65,73.90
2020-01-08,52.50,53.80,54.80,55.60,55.90,56.10,57.35,57.90,58.95,59.70,...,73.55,73.40,73.30,73.35,73.45,73.55,73.60,73.70,73.80,74.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-26,106.15,114.05,114.35,114.25,114.15,114.25,114.10,114.60,115.15,114.85,...,118.35,118.45,118.60,118.70,118.70,118.60,118.35,118.10,117.95,117.95
2024-07-29,115.25,115.20,115.30,115.50,115.90,115.90,115.95,116.50,116.20,116.15,...,120.05,120.20,120.30,120.30,120.20,119.95,119.70,119.55,119.55,119.70
2024-07-30,116.15,115.75,115.70,115.90,116.35,116.25,116.30,116.85,116.25,116.20,...,120.10,120.25,120.35,120.35,120.25,120.00,119.75,119.60,119.60,119.75
2024-07-31,116.85,116.80,116.55,116.55,117.00,117.05,117.15,117.70,117.30,117.25,...,121.45,121.60,121.75,121.70,121.60,121.35,121.10,120.95,120.95,121.10
2024-08-01,119.95,120.80,120.45,120.55,120.50,121.00,121.15,121.55,121.20,121.15,...,124.75,124.85,125.00,124.95,124.85,124.60,124.30,124.15,124.20,124.35

In [6]:
coal_inst.da_data['api2']

                  api2
datetime
2020-01-02   53.690323
2020-01-03   54.059677
2020-01-06   53.537097
2020-01-07   53.556452
2020-01-08   53.464516
...                ...
2024-07-26  107.424194
2024-07-29  115.246774
2024-07-30  116.137097
2024-07-31  116.850000
2024-08-01  120.772581

[1185 rows x 1 columns]

In [7]:
coal_inst.get_futures_curve()

In [8]:
coal_inst.data_curve['api2']

                           api2
datetime
2024-08-01 00:00:00  120.772581
2024-08-01 01:00:00  120.772581
2024-08-01 02:00:00  120.772581
2024-08-01 03:00:00  120.772581
2024-08-01 04:00:00  120.772581
...                         ...
2024-10-31 19:00:00  120.450000
2024-10-31 20:00:00  120.450000
2024-10-31 21:00:00  120.450000
2024-10-31 22:00:00  120.450000
2024-10-31 23:00:00  120.450000

[2208 rows x 1 columns]

In [9]:
coal_inst.curve_end_date

datetime.datetime(2024, 10, 31, 23, 0)

In [10]:
coal_inst.end_date_list

[datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0)]