In [1]:
# from fund_analysis.input_data.eua import Eua
from fund_analysis.input_data import Eua
import pandas as pd
import datetime as dt

In [2]:
base_products = ['W_1', 'W_2', 'W_3', 'M_1', 'M_2', 'M_3', 'Q_1', 'Q_2', 'Q_3']
base_products = ['W_1', 'W_2', 'M_1', 'M_2']
market_list = ['de', 'fr']
delivery_dict = ['base', 'peak']

# Generate the combinations
products = []
markets = []
delivery = []

for product in base_products:
    for market in market_list:
        for delivery_option in delivery_dict:
            products.append(product)
            markets.append(market)
            delivery.append(delivery_option)

params_dict = {}

params_dict['product_list'] = products

params_dict['market_list'] = markets

params_dict['delivery_list'] = delivery 

params_dict['year_list'] = [None] * len(params_dict['market_list'])
params_dict['ns'] = 2
params_dict['cont'] = False


params_dict['sD'] = dt.datetime(2020,1,1)
params_dict['eD'] = pd.to_datetime(dt.datetime.today().date())
params_dict['eD'] = dt.datetime(2024,8,1)
params_dict['ns'] = 2
params_dict['cont'] = False

In [3]:
eua_inst = Eua(params_dict)

In [4]:
eua_inst.get_da_data()

In [5]:
eua_inst.fut_matrix['eua']

              M_1    M_2    M_3    M_4    M_5
datetime
2020-01-02  24.39  24.58  24.90  25.25  25.61
2020-01-03  24.98  25.18  25.50  25.85  26.21
2020-01-06  24.23  24.43  24.74  25.09  25.45
2020-01-07  24.55  24.75  25.06  25.41  25.77
2020-01-08  24.08  24.28  24.60  24.94  25.30
...           ...    ...    ...    ...    ...
2024-07-26  67.87  70.44  72.97  76.09  79.11
2024-07-29  68.69  71.24  73.77  76.89  79.91
2024-07-30  68.64  71.18  73.73  76.79  79.81
2024-07-31  69.21  71.75  74.22  77.38  80.40
2024-08-01  71.18  73.73  76.25  79.45  82.47

[1183 rows x 5 columns]

In [6]:
eua_inst.da_data['eua']

             api2
datetime
2020-01-02  24.39
2020-01-03  24.98
2020-01-06  24.23
2020-01-07  24.55
2020-01-08  24.08
...           ...
2024-07-26  67.87
2024-07-29  68.69
2024-07-30  68.64
2024-07-31  69.21
2024-08-01  71.18

[1183 rows x 1 columns]

In [7]:
eua_inst.get_futures_curve()

In [8]:
eua_inst.data_curve['eua']

                       eua
datetime
2024-08-01 00:00:00    NaN
2024-08-01 01:00:00  71.18
2024-08-01 02:00:00  71.18
2024-08-01 03:00:00  71.18
2024-08-01 04:00:00  71.18
...                    ...
2024-10-31 19:00:00  71.18
2024-10-31 20:00:00  71.18
2024-10-31 21:00:00  71.18
2024-10-31 22:00:00  71.18
2024-10-31 23:00:00  71.18

[2208 rows x 1 columns]

In [9]:
eua_inst.curve_end_date

datetime.datetime(2024, 10, 31, 23, 0)

In [10]:
eua_inst.end_date_list

[datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0)]