In [1]:
from fund_analysis.input_data.gas import Gas
import pandas as pd
import datetime as dt

In [2]:
base_products = ['W_1', 'W_2', 'W_3', 'M_1', 'M_2', 'M_3', 'Q_1', 'Q_2', 'Q_3']
base_products = ['W_1', 'W_2', 'M_1', 'M_2']
market_list = ['de', 'fr']
delivery_dict = ['base', 'peak']

# Generate the combinations
products = []
markets = []
delivery = []

for product in base_products:
    for market in market_list:
        for delivery_option in delivery_dict:
            products.append(product)
            markets.append(market)
            delivery.append(delivery_option)

params_dict = {}

params_dict['product_list'] = products

params_dict['market_list'] = markets

params_dict['delivery_list'] = delivery 

params_dict['year_list'] = [None] * len(params_dict['market_list'])
params_dict['ns'] = 2
params_dict['cont'] = False


params_dict['sD'] = dt.datetime(2020,1,1)
params_dict['eD'] = pd.to_datetime(dt.datetime.today().date())
params_dict['eD'] = dt.datetime(2024,8,1)
params_dict['ns'] = 2
params_dict['cont'] = False

In [3]:
gas_inst = Gas(params_dict)

In [4]:
gas_inst.get_da_data()

In [11]:
gas_inst.da_data['ttf']

                ttf
datetime
2020-01-04  12.1000
2020-01-05  12.1000
2020-01-06  12.2300
2020-01-11  11.6900
2020-01-12  11.6900
...             ...
2024-07-28  32.4170
2024-07-29  32.4532
2024-07-30  33.4915
2024-07-31  33.8649
2024-08-01  34.9480

[1657 rows x 1 columns]

In [6]:
gas_inst.get_futures_curve()

In [10]:
gas_inst.data_curve['ttf']

                        ttf
datetime
2024-08-01 00:00:00  34.948
2024-08-01 01:00:00  34.948
2024-08-01 02:00:00  34.948
2024-08-01 03:00:00  34.948
2024-08-01 04:00:00  34.948
...                     ...
2024-10-31 19:00:00  37.866
2024-10-31 20:00:00  37.866
2024-10-31 21:00:00  37.866
2024-10-31 22:00:00  37.866
2024-10-31 23:00:00  37.866

[2208 rows x 1 columns]

In [8]:
gas_inst.curve_end_date

datetime.datetime(2024, 10, 31, 23, 0)

In [9]:
gas_inst.end_date_list

[datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 11, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 8, 18, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 9, 30, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0),
 datetime.datetime(2024, 10, 31, 23, 0)]